# Docker Compose que monta 4 contenedores-servicios:
#   - Contenedor httpd-alpine (mas liviano) (puerto 80) con servicio web apache. Archivos http.conf y http-vhosts.conf modificados para recibir php.
#   - Contenedor mysql (puerto 3306) con base de datos para Wordpress y Proyecto. Se agrega script para crear y rellenar la base de datos de Proyecto.
#   - Contenedor phpmyadmin (puerto 8080) que va a permitir el acceso mediante interfaz grafica web a las bbdd-s (root, deaw, wordpress).
#   - Contenedor wordpress-fpm (preconfigurado para com. con servidor web) con instalacion a iniciar (puerto 80) y descarga mediante github de carpeta Proyecto
# Volumenes:
#   - php_data: Comparte los datos de wordpres y proyecto entre cont. httpd y wordpress.
# Autor:
#   - Jose Maria Garcia Conde / DEAW04-TE02 / 24-25

services:

  httpd:
    image: httpd:alpine
    container_name: apache_server
    restart: always
    ports:
      - "80:80"
    volumes:
      - php_data:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    depends_on:
      - wordpress-fpm

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: word
      MYSQL_PASSWORD: word
    volumes:
      - ./ddbb:/docker-entrypoint-initdb.d # Script SQL para creacion de bbdd Proyecto

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"

  wordpress-fpm:
    build: ./wordpress
    container_name: wordpress_fpm
    restart: always
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: word
      WORDPRESS_DB_PASSWORD: word
      WORDPRESS_DB_NAME: wordpress
    ports:
      - "9000:9000"
    volumes:
      - php_data:/var/www/html

volumes:
  php_data:
