FROM wordpress:fpm

# Instalar Git
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Clonar el repositorio en /var/www/html/proyecto
RUN git clone https://github.com/josegarcia81/garcia_conde_jose_deaw04_te02.git /var/www/html/proyecto

# Cambiar permisos para que WordPress pueda acceder
RUN chown -R www-data:www-data /var/www/html/proyecto

# Exponer el puerto 80
EXPOSE 9000